config: Update fcm requirements introduced during EvoX 10.8 rebase
This addresses the following build error:

The following HALs in device manifest are not declared in FCM <= level 5:
  android.hardware.audio.effect@7.0::IEffectsFactory/default
  android.hardware.audio@7.0::IDevicesFactory/default
  android.hardware.boot.IBootControl/default (@1)
  android.hardware.camera.provider.ICameraProvider/internal/0 (@1)
  android.hardware.contexthub.IContextHub/default (@3)
  android.hardware.drm.IDrmFactory/clearkey (@1)
  android.hardware.drm.IDrmFactory/widevine (@1)
  android.hardware.identity.IIdentityCredentialStore/default (@4)
  android.hardware.input.processor.IInputProcessor/default (@1)
  android.hardware.memtrack.IMemtrack/default (@1)
  android.hardware.nfc.INfc/default (@1)
  android.hardware.power.IPower/default (@5)
  android.hardware.thermal.IThermal/default (@2)
  android.hardware.usb.IUsb/default (@1)
  android.hardware.vibrator.IVibrator/default (@2)
  android.hardware.wifi.IWifi/default (@2)
  android.hardware.wifi.hostapd.IHostapd/default (@2)
  android.hardware.wifi.supplicant.ISupplicant/default (@3)
  vendor.lineage.livedisplay.IPictureAdjustment/default (@1)
INCOMPATIBLE

2025-08-21 22:24:45 - check_target_files_vintf.py - INFO    : stderr: ERROR: files are incompatible: The following instances are in the device manifest but not specified in framework compatibility matrix:
    vendor.lineage.livedisplay.IPictureAdjustment/default (@1)
Suggested fix:
1. Update deprecated HALs to the latest version.
2. Check for any typos in device manifest or framework compatibility matrices with FCM version >= 5.
3. For new platform HALs, add them to any framework compatibility matrix with FCM version >= 5 where applicable.
4. For device-specific HALs, add to DEVICE_FRAMEWORK_COMPATIBILITY_MATRIX_FILE or DEVICE_PRODUCT_COMPATIBILITY_MATRIX_FILE.: Success

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/apelete/devel/evox-sunfish-a15-bp1a.repo/out/host/linux-x86/bin/ota_from_target_files/__main__.py", line 12, in <module>
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "ota_from_target_files.py", line 1582, in <module>
  File "ota_from_target_files.py", line 1553, in main
  File "ota_from_target_files.py", line 1074, in GenerateAbOtaPackage
  File "check_target_files_vintf.py", line 303, in CheckVintfIfTrebleEnabled
RuntimeError: VINTF compatibility check failed

To ease the XML rules rewritting in the future, refer to:
https://github.com/Thereache/Generate-framework-compatibility-matrix-from-fqnames#